[params]
    author = "Christian Mahnke"
    keywords = "Kleiderbügel, coat hangers, clothing storage"
    description = "Alte, schöne und fragwürdige Kleiderbügel"
    copyrightYears = "MMXXI - MMXXIII"
    cc = false
    disableScale = true

    [params.preview]
        outputPrefix = "ogPreview"
        outputSuffix = ".jpg"
        format =  "svg"
        image = "front.png"
        source = "file"
        [params.preview.size]
            height = 630
            width = 1200
        [params.preview.svg]
            template = "./Source Files/Other/preview-template.svg"
            removeMissing = true
