[params]
    author = "Christian Mahnke"
    keywords = "Kleiderbügel, coat hangers"
    description = "Eine Auswahl an alten Kleiderbügeln"
    copyrightYears = "MMXXI"
    cc = false

    [params.preview]
        outputPrefix = "preview"
        format =  "svg"
        image = "front.png"
        source = "file"
        [params.preview.size]
            height = 630
            width = 1200
        [params.preview.svg]
            template = "./Source Files/Other/preview-template.svg"
