[params]
    author = "Christian Mahnke"
    keywords = "Kinderbücher, Children's books"
    description = "Alte, schöne und fragwürdige Kinderbücher"
    copyrightYears = "MMXXI"
    cc = false

    [params.preview]
        outputPrefix = "ogPreview"
        outputSuffix = ".jpg"
        format =  "svg"
        image = "front.png"
        source = "file"
        [params.preview.size]
            height = 630
            width = 1200
        [params.preview.svg]
            template = "./Source Files/Other/preview-template.svg"
