baseURL = "https://xn--kleiderbgel-0hb.xn--blaufusstlpel-qmb.de/"
languageCode = "de"
title = "Kleiderbügel"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
rssLimit = 25
theme = ["projektemacher-base", "hugo-xml-exporter"]
copyright = "Kleiderbügel"
enableGitInfo = true
timeout = 120

[params]
    productionIIIFURLPrefix="https://xn--kleiderbgel-0hb.xn--blaufusstlpel-qmb.de/"

[languages]
  [languages.de]
    languagename = "Deutsch"

    [languages.de.menu]
      [[languages.de.menu.main]]
        name = "Start"
        weight = 1
        url = "/"

      [[languages.de.menu.main]]
        name = "Sammlung"
        weight = 2
        url = "collection/"

      [[languages.de.menu.main]]
        name = "Karte"
        weight = 3
        url = "map/"

      [[languages.de.menu.main]]
        name = "Links"
        weight = 3
        url = "links/"

      [[languages.de.menu.main]]
        name = "Suche"
        weight = 4
        url = "search/"

      [[languages.de.menu.main]]
        name = "Über"
        weight = 5
        url = "about/"


  [languages.en]
    languagename = "English"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Start"
        weight = 1
        url = "/en/"

      [[languages.en.menu.main]]
        name = "Collection"
        weight = 2
        url = "en/collection/"

      [[languages.en.menu.main]]
        name = "Map"
        weight = 3
        url = "en/map/"

      [[languages.en.menu.main]]
        name = "Links"
        weight = 3
        url = "en/links/"

      [[languages.en.menu.main]]
        name = "Search"
        weight = 4
        url = "en/search/"

      [[languages.en.menu.main]]
        name = "About"
        weight = 5
        url = "en/about/"

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "node_modules/swiper"
        target = "assets/css/swiper"

    [[module.mounts]]
        source = "node_modules/@pagefind/modular-ui/css/"
        target = "assets/scss/pagefind"

    [[module.mounts]]
        source = "node_modules/@pagefind/default-ui"
        target = "assets/js/pagefind"

   [[module.mounts]]
       source = 'static/images'
       target = 'assets/images'

#    [[module.mounts]]
#        source = 'content/post/'
#        target = 'content/post/'
#        lang= "en"

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

  [outputFormats.iiif-manifest]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-collection]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "collection"
    notAlternative = true

  [outputFormats.xml-export]
    mediaType = "application/xml"
    baseName = "xml-export"
    isPlainText = true
    notAlternative = true

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        #typographer = true
        attribute = true
        strikethrough = true

  [markup.goldmark.extensions.typographer]
          apostrophe = '&rsquo;'
          disable = false
          ellipsis = '&hellip;'
          emDash = '&mdash;'
          enDash = '&ndash;'
          leftAngleQuote = '&laquo;'
          leftDoubleQuote = '&ldquo;'
          leftSingleQuote = '&lsquo;'
          rightAngleQuote = '&raquo;'
          rightDoubleQuote = '&rdquo;'
          rightSingleQuote = '&rsquo;'

  [markup.goldmark.extensions.extras]
      [markup.goldmark.extensions.extras.insert]
          enable = true
      [markup.goldmark.extensions.extras.mark]
          enable = true
      [markup.goldmark.extensions.extras.subscript]
          enable = true
      [markup.goldmark.extensions.extras.superscript]
          enable = true

[segments]
  [segments.export]
    [[segments.export.excludes]]
      lang = 'en'
      output = '{html,rss,iiif-manifest,iiif-collection}'
      path = '{/links/**,/map/**,/about/**}'
    [[segments.export.includes]]
      kind = '{home}'
      lang = "de"
      output = '{xml-export}'

[sitemap]
  changeFreq = 'weekly'

[imaging]
    quality = 95

[outputs]
  page = ["HTML", "JSON"]

[build]
  writeStats = true

[[cascade]]
  outputs = ['html','rss', 'iiif-collection']
  [cascade._target]
    kind = "term"

[security]
  [security.http]
    mediaTypes = ['^application/json$', '^application/json;\s?charset=[uU][tT][fF]-8$', '^application/sparql-results\+json;\s?charset=[uU][tT][fF]-8$']
