baseURL = "https://xn--kleiderbgel-0hb.xn--blaufusstlpel-qmb.de/"
languageCode = "de"
title = "Kleiderbügel"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
rssLimit = 25

[params]
    author = "Christian Mahnke"
    keywords = "Kleiderbügel, coat hangers"
    description = "Eine Auswahl an alten Kleiderbügeln"
    copyrightYears = "2020"
    #stylesheets = ["https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@1&family=Nunito:ital,wght@0,400;0,700;0,900;1,400&display=swap"]
    stylesheets = []

[menu]
    [[menu.main]]
        name = "Start"
        weight = 1
        url = "/"

    [[menu.main]]
        name = "Über diese Seite"
        weight = 2
        url = "about/"

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "node_modules/jquery.flipster/dist"
        target = "assets/css/flipster"

    [[module.mounts]]
        source = "static"
        target = "static"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true
