baseURL = "https://xn--kleiderbgel-0hb.xn--blaufusstlpel-qmb.de/"
languageCode = "de"
title = "Kleiderbügel"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
rssLimit = 25
theme = ["projektemacher-base"]
copyright = "Kleiderbügel"

[menu]
    [[menu.main]]
        name = "Start"
        weight = 1
        url = "/"

    [[menu.main]]
        name = "Listenansicht"
        weight = 2
        url = "list/"

    [[menu.main]]
        name = "Über diese Seite"
        weight = 3
        url = "about/"

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "static"
        target = "static"

[mediaTypes]
  [mediaTypes."application/geo+json"]
    suffixes = ["geojson", "gjson"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/geo+json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        #typographer = true
        attribute = true
        strikethrough = true

  [markup.goldmark.extensions.typographer]
          apostrophe = '&rsquo;'
          disable = false
          ellipsis = '&hellip;'
          emDash = '&mdash;'
          enDash = '&ndash;'
          leftAngleQuote = '&laquo;'
          leftDoubleQuote = '&ldquo;'
          leftSingleQuote = '&lsquo;'
          rightAngleQuote = '&raquo;'
          rightDoubleQuote = '&rdquo;'
          rightSingleQuote = '&rsquo;'

[imaging]
    quality = 95

[outputs]
    page = ["HTML", "JSON"]
